server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servicesdb
    username: postgres
    password: ikram
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
